### ISSUE TITLE
push under windows and fht

### ISSUE THREAD

**Issue by nducros** [openspyrit/spyrit#13]
`git status` outputs

modified:   fht
modified:   spyrit/fht (untracked content)

What should I do?

Can I `git add -A` and push ? Will it break fht (e.g. under linux)?

**Comment by tbaudier** [comment]
With `git add -A` you will not add `spyrit/fht` because it's a submodule, but you will add `fht`.

To avoid `fht` symlink, maybe we can try https://stackoverflow.com/a/13631525

**Comment by nducros** [comment]
Thanks Thomas for the link. It seems a bit tricky so I'll continue staging only one or a few files at a time (no use `git add -A`)
