### ISSUE TITLE
No more images/outputs in documentation

### ISSUE THREAD

**Issue by nducros** [openspyrit/spyrit#135]
E.g., see [here ](https://spyrit.readthedocs.io/en/master/gallery/01_tuto_acquisition_operators.html)
@romainphan: Is it your last commit?

**Comment by romainphan** [comment]
That's weird... I didn't change the code, only the docstring or comments, I don't think it would have had an impact on the figures/outputs.

**Comment by romainphan** [comment]
@nducros just did a pull request that should fix it

**Comment by romainphan** [comment]
All done, it works fine
