### ISSUE TITLE
pip install spyrit > no tutorials

### ISSUE THREAD

**Issue by romainphan** [openspyrit/spyrit#142]
with user installation of spyrit (pip install spyrit), the tutorials and images don't come along
@tbaudier

**Comment by tbaudier** [comment]
With pyproject.toml branch I tried to include the tutorials. It works but, in the tutorials, there is a line:
'''
spyritPath = os.getcwd()
imgs_path = os.path.join(spyritPath, "images/")
'''
to get the image folder. But, the tutorial can be called from anywhere, so where the image folder is not present.
We can change to 
'''
spyritPath = __file__
'''
But this command is not understood by jupyter notebook
