### ISSUE TITLE
Measurement simulation (in meas.py)

### ISSUE THREAD

**Issue by romainphan** [openspyrit/spyrit#146]
Instead of having `LinearDynamic` inheriting of `Linear`, what about having `Linear`inheriting of `LinearDynamic` ? To me this seems logical because looking at a still picture is a particular case of a moving picture. 
Also, the adjoint / pinv methods that we currently inherit from Linear would be redefined only in the child class, which would avoid having useless methods.
@nducros ?

**Comment by nducros** [comment]
It makes sense but this risky. Hum... What about a first version with no heritage?

**Comment by nducros** [comment]
done
