### ISSUE TITLE
self.reconstruct() and self.reconstructuct_pinv() in class PinvNet in recon.py are identical

### ISSUE THREAD

**Issue by romainphan** [openspyrit/spyrit#153]
In recon.py, class PinvNet, methods [reconstruct()](https://github.com/openspyrit/spyrit/blob/38020915b1100ef3de8e18b10ba0d4b1695f6d72/spyrit/core/recon.py#L419C1-L419C30) and [reconstruct_pinv()](https://github.com/openspyrit/spyrit/blob/38020915b1100ef3de8e18b10ba0d4b1695f6d72/spyrit/core/recon.py#L459) are identical, the only difference being the final denoising operation :

`return self.denoi(x)` in  reconstruct()

 `return x` in reconstruct_pinv()

The docstring are also identical. We should:
1. Merge both functions so that the one using the denoising calls the other
2. update the docstring so that the user sees the difference

Unless there is some mistake in the code ? A lot of computations have been commented so it might be that.
@nducros @tbaudier any idea on this one ?

**Comment by romainphan** [comment]
The commit you're talking about dates back to April 2023... Hasn't it been integrated since then ?

**Comment by nducros** [comment]
I agree with both points.
NB : PinvNet belongs to a wider class of two-step networks where the first step is fixed while the second is learned. DCNet is another two-step network.
