### ISSUE TITLE
Integrate changes for a script

### ISSUE THREAD

**Issue by romainphan** [openspyrit/spyrit#155]
`Example:`
        `>>> H_pos = np.random.rand(24,64)`
        `>>> H_neg = np.random.rand(24,64)`
        `>>> linop = LinearRowSplit(H_pos,H_neg)`

[Is this correct](https://github.com/openspyrit/spyrit/blob/e55ed09bceb17c915d1ce84fc652393c333b380c/spyrit/core/meas.py#L407) ? or should each matri H_pos and H_neg be positive as follows:

`Example:`
        `>>> H = np.random.rand(24,64)`
        `>>> H_pos[H > 0] = H[H > 0]`
        `>>> H_neg[H < 0] = -H[H < 0]`
        `>>> linop = LinearRowSplit(H_pos,H_neg)`
@tbaudier

**Comment by nducros** [comment]
The class can be removed.

The idea will be to merge the [hspim branch](https://github.com/openspyrit/spyrit/tree/hspim) in order to run this [script](https://github.com/openspyrit/spyrit-examples/blob/master-seb/2023_Optica/main_recon_net_EGFP-DsRed_14_all_slices.py)

**Comment by romainphan** [comment]
The class LinearRowSplit will be removed.

Concerning the merge, what exactly should be merged ?

**Comment by nducros** [comment]
[hspim branch](https://github.com/openspyrit/spyrit/tree/hspim) with `master `such that this [script](https://github.com/openspyrit/spyrit-examples/blob/master-seb/2023_Optica/main_recon_net_EGFP-DsRed_14_all_slices.py) runs
