### ISSUE TITLE
Matrix multiplication in meas.py

### ISSUE THREAD

**Issue by romainphan** [openspyrit/spyrit#157]
### Facts:
In meas.py, the "linear measurements" are done using a `torch.Linear` object, which is then callable. Input vectors can be passed to them and are multiplied by the matrix stored in the `torch.Linear` object.

### Question:
Is it possible to replace the architecture revolving around the `torch.Linear` object by a simple matrix multiplication ? It would be much simpler to implement and possibly faster to compute. However, I'm afraid some bits of code might malfunction, although if all the methods and attributes are properly redefined to avoid any reference to a `torch.Linear`, I don't see why it wouldn't work.
Do you have any comments to make on this replacement ? @nducros

**Comment by nducros** [comment]
I've been in favor of the matrix multiplication for a couple of years. 
1. This requires careful testing.
2. Will it be faster?
3. Handling GPU computation may be tricky, but not that much using `register_buffer` see [here](https://github.com/openspyrit/spyrit/blob/e55ed09bceb17c915d1ce84fc652393c333b380c/spyrit/core/prep.py#L41)
