### ISSUE TITLE
double definition of "Permutation_Matrix", in spyrit.misc.matrix_tools and spyrit.misc.sampling

### ISSUE THREAD

**Issue by romainphan** [openspyrit/spyrit#176]
### Issue
Double definition of the same function, in `spyrit.misc.matrix_tools` and in `spyrit.misc.sampling`. Both definitions are identical, the first one doesn't seem to be used in any other file.

### Suggestion
Should we eventually remove `spyrit.misc.matrix_tools.Permutation_Matrix` ? 
I think we should first link `spyrit.misc.matrix_tools.Permutation_Matrix` to `spyrit.misc.sampling.Permutation_Matrix` and print a user warning, then in a few months the function could be effectively removed.

**Comment by nducros** [comment]
`Permutation_Matrix` still in use HadamSplit (and elsewhere?)

Idea :  Remove `Perm` everywhere, keep the corresponding indices as an nn.parameters.

**Comment by romainphan** [comment]
The function in matrix_tools has been linked to the one in sampling.
