### ISSUE TITLE
Add test 2021_OpticsExpress + update 2020_ISBI in CI

### ISSUE THREAD

**Issue by nducros** [openspyrit/spyrit#18]

**Comment by tbaudier** [comment]
Try to add the OpticsExpress example. For the moment there is a bug:
https://github.com/openspyrit/spyrit/runs/3114027021?check_suite_focus=true#step:7:53

It seems that the data https://github.com/openspyrit/spyrit-examples/blob/master/2021_Optics_express/Experimental_Data_Processing_review.ipynb?short_path=cc5656f#L486 is not available

**Comment by nducros** [comment]
I think we did put everything in https://www.creatis.insa-lyon.fr/~ducros/spyritexamples/2021_OpticsExpress/
Still missing something ?

**Comment by tbaudier** [comment]
Done https://github.com/openspyrit/spyrit/pull/27
