### ISSUE TITLE
Double extension name in core.train

### ISSUE THREAD

**Issue by nducros** [openspyrit/spyrit#187]
1. Reconstruction with pinv + CNN is not working. Is it due to the model path `*7.pth.pth`?
2. In any cas, update the function that loads the models to handle both arguments `model` and `model.pth`

**Comment by romainphan** [comment]
tuto 3 now working in master

double extension .pth.pth is WIP

**Comment by romainphan** [comment]
Behavior corrected. 
core.train.load_net and save_net now must have the file extension specified.
