### ISSUE TITLE
Documentation source files are versionned

### ISSUE THREAD

**Issue by nducros** [openspyrit/spyrit#196]
Some folders have been included by mistake 
* [_autosummary](https://github.com/openspyrit/spyrit/tree/master/docs/source/_autosummary)
* [_static/css](https://github.com/openspyrit/spyrit/tree/master/docs/source/_static/css)
* [_templates](https://github.com/openspyrit/spyrit/tree/master/docs/source/_templates)
* [api/generated/backreferences](https://github.com/openspyrit/spyrit/tree/master/docs/source/api/generated/backreferences)
* [html](https://github.com/openspyrit/spyrit/tree/master/docs/source/html)
* ... ?

@romainphan: Please discuss it with Thomas, as removing the files does not remove them from the history.

**Comment by nducros** [comment]
I removed them from version control *not* from history and included some folders to the .gitignore file.

**Comment by tbaudier** [comment]
I did a branch :

I removed that folder from the history and put them in .gitignore. The docs is here:

**Comment by romainphan** [comment]
everything correct now ? 

_templates has to be kept (it determines the .rst files for the automatic documentation)
_static/css could have been kept (it determines the css for the tutorial homepage - but it is optional)
the others have been correctly deleted

**Comment by nducros** [comment]
I am not sure about _templates. You can check the [doc from my branch](https://spyrit.readthedocs.io/en/clean_tuto_cdnet_drunet/_autosummary/spyrit.core.meas.DynamicLinear.html). I deleted _templates but I cannot see what's missing.

**Comment by nducros** [comment]
I agree for _templates :) 
What about \docs\source\sg_execution_times.rst
