### ISSUE TITLE
Spyrit is getting big...

### ISSUE THREAD

**Issue by nducros** [openspyrit/spyrit#197]
... too big! (.git folder is ~500 MiB)

We should have a look at it. 
* It may be only related to the documentation files, maybe not
* We have only few figures but we often modify them

**Comment by tbaudier** [comment]
In this branch https://github.com/openspyrit/spyrit/tree/clean it's 8.2M

**Comment by romainphan** [comment]
it is solved now ?

**Comment by nducros** [comment]
@tbaudier Could you check that master is small as well?

**Comment by tbaudier** [comment]
12M

**Comment by nducros** [comment]
Cool ! 
Mais il faut peut-être y aller mollo avec les schémas. Tu en penses quoi @tbaudier ?
