### ISSUE TITLE
typo main github page (link problem)

### ISSUE THREAD

**Issue by nducros** [openspyrit/spyrit#211]
SPyRiT is a PyTorch <https://pytorch.org/>_-based deep image reconstruction package primarily designed for single-pixel imaging.

**Comment by romainphan** [comment]
the link works propertly, i don't see what typo you're talking about

**Comment by nducros** [comment]
Look [here](https://github.com/openspyrit/spyrit). 
Qqs retours à la ligne inattendus dans les shapes [ici](https://spyrit.readthedocs.io/en/romain_dev_from_clean/_autosummary/spyrit.misc.sampling.sort_by_significance.html#spyrit.misc.sampling.sort_by_significance). 
Sinon ça me parait top !

**Comment by romainphan** [comment]
Link corrected in [this commit](https://github.com/openspyrit/spyrit/commit/f2ee4e53681d0f4c1557c23dd746940936d1824b)
