### ISSUE TITLE
Tuto 8 too much memory consumption

### ISSUE THREAD

**Issue by romainphan** [openspyrit/spyrit#218]
Tuto 8 needs too much memory to run on ReadtheDocs, the documentation fails.

I think this is due to the large LPGD to download (2GB). I suggest we don't download it, and to display the reconstructed image we save it locally and display it.

**Comment by nducros** [comment]
This sounds good. Let's save it somewhere and download it though. I think we should stop adding figures.

**Comment by romainphan** [comment]
Great, what do you think of storing it on the nextcloud server ? We already have some figures stored there

**Comment by nducros** [comment]
Okay. What's the link?
