### ISSUE TITLE
Training : GPU usage fluctuating

### ISSUE THREAD

**Issue by romainphan** [openspyrit/spyrit#222]
Is there a way to always use as much GPU as possible during training phase ? Same with different cores of the CPU ?

**Comment by romainphan** [comment]
Maybe : https://discuss.pytorch.org/t/unstable-gpu-utilization-when-training-resnet/143507/7
--> https://on-demand.gputechconf.com/gtc-cn/2019/pdf/CN9951/presentation.pdf
--> https://github.com/NVIDIA/nsight-training

**Comment by nducros** [comment]
Usually I tend to increase the batch size till I reach the maximum memory available. Not sure this answers your question...
