### ISSUE TITLE
TikhonovMeasurementPriorDiag

### ISSUE THREAD

**Issue by romainphan** [openspyrit/spyrit#228]
change name to TikhoDC ?

**Comment by romainphan** [comment]
I plan to release v2.3.3 tomorrow. I suggest the following :
- starting to remove Denoise_layer (DeprecationWarning) (internally, it is used only in TikhonovMPD)
- still update its documentation so it is clear
- do the denoising internally in TikhonovMPD

any thoughts on this ?

**Comment by romainphan** [comment]
https://github.com/openspyrit/spyrit/issues/219

**Comment by nducros** [comment]
Should be simplify in next release

**Comment by romainphan** [comment]
Denoise_layer can now be removed (and will be removed in a future version). 
TikhonovMeasurementPriorDiag now handles everything
