### ISSUE TITLE
training dcnet

### ISSUE THREAD

**Issue by WH-CSU** [openspyrit/spyrit#236]
Dear Author, Is it convenient to share the training files of dcnet? The existing trained dcnet is not able to satisfy my requirement.
Looking forward to your reply and good luck!

**Comment by nducros** [comment]
Hi, 

The general training procedure is explained in this tutorial: 
https://spyrit.readthedocs.io/en/master/gallery/tuto_04_train_pseudoinverse_cnn_linear.html

You can also check the specifics of the DCNet workflow of the original paper:
https://github.com/openspyrit/spyrit-examples/blob/master/2022_OE_spyrit2/train.py

Hope this helps.

**Comment by romainphan** [comment]
Hi again @WH-CSU , did you find your answer ?
