### ISSUE TITLE
Experimental results input

### ISSUE THREAD

**Issue by WH-CSU** [openspyrit/spyrit#240]
Dear authors, Is the use of this program for processing the results of an experiment reading in the y-values? (Sampling order is consistent with simulation)
Is there a program to read the y-value of an experiment and denoise it using this network?

**Comment by romainphan** [comment]
Hello, in [spyrit.core.recon](https://spyrit.readthedocs.io/en/master/_autosummary/spyrit.core.recon.html) you can find several classes (PinvNet being the most simple one, DCNet and LearnedPGD) that contain a `reconstruct_expe` method that specifically reconstructs images from measurements.

**Comment by romainphan** [comment]
Hi again, did this help you ?

**Comment by romainphan** [comment]
I'm closing this issue, but feel free to reopen it or another one if you need any help.
