### ISSUE TITLE
pip install spyrit fails on MacOS (High Sierra)

### ISSUE THREAD

**Issue by cmouton** [openspyrit/spyrit#30]
I followed Thomas's recommendation : no more using the cache.
But it is still downloading the .tar.gz and failing.

Is it because there is no wheel for MacOS (High Sierra)?
<img width="1423" alt="Screen Shot 2021-07-21 at 13 17 53" src="https://user-images.githubusercontent.com/583625/126480738-f7773924-533b-4b2e-938d-8deba54b38b8.png">

**Comment by tbaudier** [comment]
Can you tell us the python version please ?

The wheel are available for python 3.6 -> 3.8 (https://pypi.org/project/spyrit/#files). I can add python 3.9 now. But for older python, spyrit will not work

**Comment by cmouton** [comment]
Here is the version : 
(2021_DLMIS_Hands-on_test) (base) ei-cm-566:virtualenv clairemouton$ python --version
Python 3.7.3

Thanks for the link.
I saw that MacOSX is supported for 10.14, but mine is 10.13.6... That should be the reason of the failure.
