### ISSUE TITLE
version 0.14 not present on pypi

### ISSUE THREAD

**Issue by tbaudier** [openspyrit/spyrit#33]
@nducros the pypi version was not updated with version 0.14
https://pypi.org/project/spyrit/

The version has to be changed here:
https://github.com/openspyrit/spyrit/blob/master/setup.py#L45

**Comment by tbaudier** [comment]
Done with https://github.com/openspyrit/spyrit/commit/36c90d10e9ca4d82671d24d68db8257a4b8e1c4d

**Comment by nducros** [comment]
@tbaudier Thanks! If I understand correctly, `setup.py` has to be updated manually after a new version is tagged?

**Comment by tbaudier** [comment]
Exactly, but before, not after.
You have the procedure here:
https://github.com/openspyrit/spyrit#versioning

**Comment by nducros** [comment]
So cool :)
