### ISSUE TITLE
Remove fht

### ISSUE THREAD

**Issue by tbaudier** [openspyrit/spyrit#35]
In https://github.com/openspyrit/spyrit/issues/29

@nducros 
> Great. So this is the right time to discard it!
> 
> You should only need to replace this [line ](https://github.com/openspyrit/spyrit/blob/36c90d10e9ca4d82671d24d68db8257a4b8e1c4d/spyrit/learning/model_Had_DCAN.py#L561) with
> `H = wh.walsh2_matrix(n)/n`
> 
> Both `Stat_h` and `optim_had `are no longer necessary as I reimplemented the walsh version of both functions (already included)

I started a new branch here
https://github.com/openspyrit/spyrit/pull/34

**Comment by tbaudier** [comment]
How can I remove the function `fht2` in these files:
https://github.com/openspyrit/spyrit/blob/master/spyrit/misc/pattern_choice.py#L224
https://github.com/openspyrit/spyrit/blob/master/spyrit/learning/model_Had_DCAN.py#L54
https://github.com/openspyrit/spyrit/blob/master/spyrit/reconstruction/basic_hadamard.py#L32

**Comment by nducros** [comment]
> https://github.com/openspyrit/spyrit/blob/master/spyrit/misc/pattern_choice.py#L224
keep it as it is for now. Maybe write down somewhere that this function should be updated

> https://github.com/openspyrit/spyrit/blob/master/spyrit/learning/model_Had_DCAN.py#L54
Do not need the function anymore

> https://github.com/openspyrit/spyrit/blob/master/spyrit/reconstruction/basic_hadamard.py#L32
`fht2(X)` --> `wh.walsh2(X,H)/len(X)` with `H = walsh_matrix(len(X))` outside the `for` loop

**Comment by guilhermebene** [comment]
@tbaudier We have accepted PR #34, but there are still traces of fht in the `README`, `setup.py`, `.gitmodules`, `.github/workflows/main.yml`, and the symbolic link. Can you take care of this in the future?
