### ISSUE TITLE
Renaming of walsh_ordered

### ISSUE THREAD

**Issue by cmouton** [openspyrit/spyrit#40]
Hello,
It seems that some methods related to Hadamard have been renamed, causing the deprecation of some code.

For example, [here](https://github.com/openspyrit/spyrit/blob/20e5c76f84edeb84e566cf26c90b63911fb42781/spyrit/misc/statistics.py#L90) 
and [there](https://github.com/openspyrit/spyrit/blob/ac378472327ba6b1575628088dadaeadbc2cc0a3/spyrit/reconstruction/walsh_ordered_recon.py#L17)

walsh_ordered is called but I could not find a definition of walsh_ordered.

Probably walsh_ordered should be replaced by its new name?

**Comment by nducros** [comment]
Sure. You can use `walsh2`, `iwalsh2` or the torch version of it `walsh2_torch`

**Comment by cmouton** [comment]
The documentation was missing :
<img width="515" alt="Screen Shot 2021-10-04 at 11 11 39" src="https://user-images.githubusercontent.com/583625/135831707-451f3ce0-eb2e-49c6-9662-450a9f71e7ca.png">

**Comment by cmouton** [comment]
I replaced walsh_ordered by walsh2 and now the following warning disappeared 👍
<img width="1076" alt="Screen Shot 2021-10-04 at 11 11 04" src="https://user-images.githubusercontent.com/583625/135831960-f66c7ed6-71b7-47d5-889f-865a6ff9945d.png">

**Comment by cmouton** [comment]
And the documentation is generated through sphinx 👍 
<img width="601" alt="Screen Shot 2021-10-04 at 11 29 27" src="https://user-images.githubusercontent.com/583625/135832060-d6cbf0f7-0a20-4651-b339-1cb05d2f8bbe.png">

**Comment by cmouton** [comment]
This issue is solved 👍
