### ISSUE TITLE
builds are back

### ISSUE THREAD

**Issue by nducros** [openspyrit/spyrit#59]
P... Je me suis fais avoir sur towards_v2 ! Je pensais être sur "ma" branche et aussi que towards_v2 était protégée, mais non. 
Je suis vraiment confus Thomas, j'aurais dû vérifier je connais la procédure maintenant

@TALAOUI : Ne pull pas surtout !

**Comment by tbaudier** [comment]
Dis moi si c'est ok pour toi

La branche est protégée mais pas pour les admin https://stackoverflow.com/a/57998309  dont tu fais parti.

Pour etre sur d'etre sur towards_v2, fait un git reset --hard origin/master

**Comment by TALAOUI** [comment]
Hello,

Pas de pull de mon côté no soucy. Je reviens vers vous rapidement en début
de semaine pro pour savoir ce quon fait.

A+

Le jeu. 29 sept. 2022 à 16:48, Nicolas Ducros ***@***.***> a
écrit :
